{{- if .Values.platformInit.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: platform-init
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: platform-init
          image: {{ .Values.platformInit.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command: ["sh", "-lc", "npx prisma db push --schema prisma/schema.prisma && npm run db:seed"]
          envFrom:
            - configMapRef: { name: platform-config }
            - secretRef: { name: platform-secrets }
{{- end }}
