apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: enterprise-platform
  namespace: argocd
spec:
  description: Enterprise platform project
  sourceRepos:
    - '*'
  destinations:
    - namespace: enterprise-platform
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
